### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by aniforprez**
Updated README to show example of hidden segments within BULLETTRAIN_PROMPT_ORDER

### CODE REVIEW

**Comment by dawikur** [comment]
Looks good for me. Maybe example will make it easier :+1: 
@caiogondim What do you think?

**Comment by aniforprez** [comment]
I was considering adding a table with all the possible segments and a short description of each. Would that be good?

**Comment by vadviktor** [comment]
I think available segments need their documentation extended of what they really do, with images maybe for the visual and they lack their "call word", like "nvm" for nodejs.

**Comment by aniforprez** [comment]
Closing this

**Pull request closed without merging**
