### PR TITLE
Fetch git repos automagically

### PR DESCRIPTION
**Pull request by gilmrjc**
Fetch the git repos to show the up-to-date info in the bar

### CODE REVIEW

**Comment by dawikur** [comment]
This can increase time of showing prompt. And what if remote is inaccessible? 
For me prompt needs to be as fast as possible, and clear as well. Sorry but :-1:  from me.

**Comment by caiogondim** [comment]
This will indeed have an impact in performance.
Do we see value on implementing this under a feature flag?

**Comment by gilmrjc** [comment]
You are right, this makes the prompt slow and I ran into the not network problem, but I find this useful to keep my prompt up-to-date without worrying about it. The fetch is only done in dirs with a git repo, so if you are outside your repos this should not affect performance.

I think I should implement a network test before the fetch and it seems fair to make this optional using a flag.

**Comment by dbkaplun** [comment]
I personally use the prompt under [antigen](https://github.com/zsh-users/antigen) which will automatically keep the repo up-to-date. FYI

**Comment by dawikur** [comment]
This can still take up to 1s on network fail, more if a lot of data is needed to fetched. Why pinging 8.8.8.8? This is some magic git IP?

Anyway, we still need documentation for `BULLETTRAIN_GIT_FETCH `in **OPTIONS**

**Comment by gilmrjc** [comment]
I can make the timeout shorter but 1 second seems fair to me. It only does the check inside a repo, and it does the fetch in the background, so if you are outside a repo or have network access you won't notice it. The downsides are you will see the new status after the fetch, not immediately, and it will slow down the prompt if you don't have network access (only inside a repo dir). For this reason the option is disabled for default and anyone who want to use it must activate it.

About 8.8.8.8 this is the Google DNS IP. It should be a stable IP in the net. I don't know how I can check network access in a cross-platform way that don't require access to another machine, and this IP never change and it's well known so that's why I choose it. It can be changed to a DNS root  and it should still work.

**Comment by vadviktor** [comment]
Features like this IMHO are not the task of a prompt theme. Such a feature really should be a task for a zsh plugin. Just ask yourself, is this why you install a theme for, to automate git?

**Comment by dawikur** [comment]
@vadviktor  has a point, really good one. let one thing do one thing, and prompt/theme isn't something to update your repo/system/drive.

**Comment by dawikur** [comment]
Can we close this one?

**Comment by vadviktor** [comment]
I for one don't want such functionality added to a theme and wish to keep a theme being a "reporting" tool, not a swiss army knife. I'm closing it for now, feel free to keep the discussion going if you wish to find a way to do such things outside the scope of the theme.

**Pull request closed without merging**
