### PR TITLE
Only show the ruby segment if in ruby project folder, only show node if in node project folder

### PR DESCRIPTION
**Pull request by MichaelTaylor3D**
This makes it so the relevant information only shows up when you need it.
When you enter a directory that is a ruby project, the ruby segment will show up.
When you enter a directory that is a node project, the node segment will show up.
These segments are hidden if you are not in either type of project.

### CODE REVIEW

**Comment by gregf** [comment]
:+1:

**Comment by vadviktor** [comment]
@MichaelTaylor3D, will I be able to enforce their presence still with a config flag? I need to see the ruby version outside a project too. Thanks!

**Comment by MichaelTaylor3D** [comment]
good point, Ill add in a config option to set "only show in project" to true or false

**Comment by vadviktor** [comment]
@MichaelTaylor3D I also noticed that you only consider projects with Rails. If so then I'd suggest making it clear in the docs and/or adjust the naming of your option flags accordingly. :) An example, I have Sinatra and plain Ruby projects too.

Just thinking out loud here, if you aim for a "project" detection, wouldn't it be easier to check for the `.ruby-version` file?

**Comment by alexlafroscia** [comment]
:+1: for checking for `.ruby-version` or `Gemfile` instead of `rails` in the dependency list

**Comment by caiogondim** [comment]
There is an error if there is no `bundle`, or `rails` or `npm` installed.
We have to check those cases as well.

And +1 for checking `.ruby-version` or `Gemfile`.

**Comment by caiogondim** [comment]
@MichaelTaylor3D Still waiting for the fix =)

**Comment by vadviktor** [comment]
This is just too old and since we are moving over to the new Go project  ( #236 ) it will have more space to elaborate on such features in https://github.com/bullettrain-sh/bullettrain-go-ruby. Closing now.

**Pull request closed without merging**
